### PR TITLE
rewrites and optimisations

### PR DESCRIPTION
**Pull request by iwa**
this PR contains a lot of little changes, mostly architectural :

- update the tsconfig file
- reformat all the code
- optimize some imports
- create a mother class Bot
- rewrite code to use Bot class

### CODE REVIEW

**Comment by Hyperfresh** [comment]
Just checked out the PR on my computer and running into several execution issues (it builds fine though)

- use "build and debug" action (see `./.vscode/launch.json`)
image

- "build and debug" again with `"type": "module"` in `./package.json`
image

- use VS Code's tsc watch and use "launch without build" action
image

- remove `"type": "module"` in `./package.json` and "launch without build" again
image
Changing the `Bot.ts` code so it waits for configuration and database to set up first does not seem to fix the issue.

Unsure on what the issue is here...

**Comment by iwa** [comment]
i'm gonna check that now

**Comment by iwa** [comment]
alright so i've done a bit of testing, it seems that your vscode scripts are a bit broken somehow
when building and running the code with the "build & run" script, i also run into this issue

```bash
Uncaught SyntaxError /Users/iwa/dev/Hylybot/src/index.ts:1
import Bot from './Bot';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:822:12)
    at executeUserEntryPoint (node:internal/modules/run_main:77:12)
    at <anonymous> (node:internal/main/run_main_module:17:47)
```

but when i compile the code by myself (`yarn tsc && node build/index.js`), it runs fine

also you should make some of your command a bit more modular, if you don't have all the api keys the bot requires, and use the code as it is, its a bit of a pain to run the bot for testing ^^'

**Comment by Hyperfresh** [comment]
Mhm, yep. Probably the biggest thing I need to modularise is the Profiles function. I've made the buttons function modular but I should get round to doing most of its functions in a modular fashion as well...

**Review by Hyperfresh — APPROVED** [review]
LGTM. Did make a few extra cleanups where Beautify didn't clean up the code well.

I should probably work on making the bot more modular and easier to understand w/ comments, but that's for me to figure out ^u^

**Comment by iwa** [comment]
> LGTM. Did make a few extra cleanups where Beautify didn't clean up the code well.
> 
> I should probably work on making the bot more modular and easier to understand w/ comments, but that's for me to figure out ^u^

yup you should definitely try! it'll make your code way more cleaner and easier to maintain in the future
try to find your own way, by taking inspiration on other discord bots code for eg, and after alot of thinking you'll eventually find a good way for you
i could try to implement my "way of thinking and moduling" in a PR so you could see how i do things when i get some free time

**Pull request merged**
